
# Notes on Numpy Vector

In [1]:
import numpy as np
a = np.random.rand(5)

In [2]:
print(a)

[0.99845208 0.39922604 0.22282419 0.02298804 0.4627359 ]


In [3]:
a.shape # Rank 1 Array

(5,)

In [4]:
print(a.T)

[0.99845208 0.39922604 0.22282419 0.02298804 0.4627359 ]


In [5]:
print(np.dot(a, a.T))

1.4205915704605914


In [6]:
# Column Vector
a = np.random.rand(5, 1)

In [7]:
print(a)

[[0.50070874]
 [0.57477748]
 [0.47935124]
 [0.27917577]
 [0.75929904]]


In [8]:
# Menentukan Transpose (T)
print(a.T)

[[0.50070874 0.57477748 0.47935124 0.27917577 0.75929904]]


In [9]:
print(np.dot(a, a.T))

[[0.25070924 0.28779611 0.24001536 0.13978575 0.38018767]
 [0.28779611 0.33036915 0.2755203  0.16046395 0.43642799]
 [0.24001536 0.2755203  0.22977761 0.13382325 0.36397094]
 [0.13978575 0.16046395 0.13382325 0.07793911 0.2119779 ]
 [0.38018767 0.43642799 0.36397094 0.2119779  0.57653504]]


In [10]:
# Begitu pula dengan row Vector

# Row Vector
a = np.random.rand(1, 5)

print(a)

[[0.96497398 0.15826423 0.55490673 0.22235132 0.02006083]]
